# Generated by Django 4.2.2 on 2023-06-23 05:25

import django.core.validators
from django.db import migrations, models
import plants.auth_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=10, validators=[plants.auth_app.validators.check_starts_capital])),
                ('last_name', models.CharField(max_length=10, validators=[plants.auth_app.validators.check_starts_capital])),
                ('picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
